### ISSUE TITLE
Release version 0.2.X to npm

### ISSUE THREAD

**Issue by felipesabino** [hakobera/mongobq#48]
Current npm version is [`0.1.4`](https://www.npmjs.com/package/mongobq) and [`package.json` says 0.2.0](https://github.com/hakobera/mongobq/blob/master/package.json#L4).

From the commit log it seems that there were a lot of important changes like gcloud update and [node 0.10 support drop](https://github.com/hakobera/mongobq/commit/5e7460f966bd1b0eee79132fbf4afd4e49191b3b#diff-04c6e90faac2675aa89e2176d2eec7d8L4)

Besides this inconsistency, I don't know to which exact codebase npm is currently pointing to, as the repo also lacks tags for each version. I also don't know the last stable release as there were updates after `0.2.0` version bump that did not resulted in a new release.

**Comment by hakobera** [comment]
@felipesabino Sorry for confusion. I'm internally tested v0.2.0 before release to npm.
And now I release version 0.2.0 to npm! Please try it.

And I also add tag 0.1.4 and 0.2.0 to clear to which code is release to npm.
Thanks for your comment.
